#!/usr/bin/env node
/**
 * make-sitemap.mjs — regenerate sitemap.xml.
 *
 * The only interesting field is <lastmod>, and a hand-maintained one is worse
 * than none: a date that never moves teaches crawlers to ignore the whole
 * file. So each page's lastmod is read from git — the commit date of the last
 * commit that touched that page's HTML — rather than typed in.
 *
 *   npm run sitemap        # after changing a page, before committing
 *
 * Run it as part of the same commit as the page edit and the date lands one
 * commit behind; that is close enough, and it is self-correcting on the next
 * change. Needs full git history, so it runs here rather than in CI (which
 * checks out shallow).
 */
import { writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = "https://1khz.sh";

// Priority is a hint about relative importance within the site, nothing more.
// The generator is the front door; the calculators are the reason to come
// back; /math/ and /about/ exist to be trusted rather than found.
const PAGES = [
  { path: "",      priority: "1.0" },
  { path: "delay", priority: "0.8" },
  { path: "db",    priority: "0.8" },
  { path: "rt60",  priority: "0.8" },
  { path: "note",  priority: "0.8" },
  { path: "spl",   priority: "0.8" },
  { path: "math",  priority: "0.6" },
  { path: "about", priority: "0.6" },
];

const today = new Date().toISOString().slice(0, 10);

/** Commit date (YYYY-MM-DD) of the last change to a file, or today's date. */
const lastCommit = (file) => {
  try {
    const out = execFileSync("git", ["log", "-1", "--format=%cs", "--", file],
                             { cwd: ROOT, encoding: "utf8" }).trim();
    return /^\d{4}-\d{2}-\d{2}$/.test(out) ? out : today;
  } catch {
    return today; // no git, or a file that has never been committed
  }
};

const entries = PAGES.map(({ path, priority }) => {
  const file = path ? `${path}/index.html` : "index.html";
  const loc = `${SITE}/${path ? `${path}/` : ""}`;
  return `  <url>\n` +
         `    <loc>${loc}</loc>\n` +
         `    <lastmod>${lastCommit(file)}</lastmod>\n` +
         `    <priority>${priority}</priority>\n` +
         `  </url>`;
}).join("\n");

writeFileSync(`${ROOT}/sitemap.xml`,
`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/make-sitemap.mjs — run \`npm run sitemap\`. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`);

console.log(`Wrote sitemap.xml — ${PAGES.length} URLs.`);
